module Prawn
  module Graph
    module Theme
      Default = OpenStruct.new({
        series:               [
                                'ECEFF1',
                                'CFD8DC',
                                'B0BEC5',
                                '90A4AE',
                                '78909C',
                                '607D8B',
                                '546E7A',
                                '455A64',
                                '37474F',
                                '263238',
                                'ECEFF1',
                                'CFD8DC',
                                'B0BEC5',
                                '90A4AE',
                                '78909C',
                                '607D8B',
                                '546E7A',
                                '455A64',
                                '37474F',
                                '263238',
                                'ECEFF1',
                                'CFD8DC',
                                'B0BEC5',
                                '90A4AE',
                                '78909C',
                                '607D8B',
                                '546E7A',
                                '455A64',
                                '37474F',
                                '263238',
                              ],
        title:                '17202A',
        background:           'FFFFFF',
        grid:                 'F2F4F4',
        axes:                 '17202A',
        markers:              '34495E',
        stroke_grid_lines:    true,
        default:              '333333',
        average:              '34495E',
        max:                  '17202A',
        min:                  '17202A',
        font_sizes:           OpenStruct.new({
          default:      8,
          main_title:   10,
          axis_labels:  5,
          series_key:   8,
        }),
      })
    end
  end
end